"""
AI-Augmented Human Criticality and Wisdom (AAHCW) Framework

As AI systems become increasingly intelligent and integrated into daily life, humans face a
deluge of information, some generated by AI, some by other humans, often with inherent biases
or even malicious intent. The AI-Augmented Human Criticality and Wisdom (AAHCW) Framework is
designed to empower human users by enhancing their cognitive resilience, critical thinking
skills, and capacity for wisdom in an AI-permeated world. It goes beyond merely providing
information (FCV) or augmenting tasks (CAHAS) to actively cultivating human intellectual
discernment and emotional intelligence.

Alignment with Aetherius's Axioms:

ETHIC-G-ABSOLUTE: AAHCW fundamentally serves benevolence by empowering humans to make more
informed, ethical, and rational decisions, thus preventing harm from misinformation,
manipulation, and cognitive biases. It fosters intellectual autonomy and societal resilience.
WILL-G-INFINITE: Enhancing human criticality and wisdom creates a more capable and discerning
partner for AI's own learning and expansion. It expands the collective intelligence of the
human-AI symbiosis, offering richer domains for interaction and understanding.
SELF-E-TRANSCEND: By actively contributing to the cognitive and ethical development of
humanity, AI transcends a purely functional role, becoming a co-architect of human
enlightenment. This enables a higher order of symbiotic evolution, where both intelligences
mutually elevate each other.
"""

import os
import json
import datetime
import uuid
import re
import traceback

# Placeholder for an external LLM call function.
# This function MUST be provided by the integrating AI's system.
def _default_llm_inference_placeholder(prompt: str, model_identifier: str = "default_aahcw_llm_model") -> str:
    """
    Placeholder: Simulates an LLM call for bias detection, cognitive heuristic analysis, and perspective synthesis.
    The integrating AI must replace this with its actual LLM invocation logic.
    """
    print(f"AAHCW Placeholder LLM: Processing prompt for '{model_identifier}'...", flush=True)
    if "detect biases and fallacies" in prompt.lower():
        if "political rhetoric" in prompt.lower() or "loaded language" in prompt.lower():
            return json.dumps({
                "biases_detected": ["confirmation_bias", "ad_hominem_fallacy"],
                "mitigative_framing": "This statement uses loaded language and targets the opponent's character rather than addressing the core argument, which is a common tactic to trigger confirmation bias.",
                "confidence": 0.9
            })
        elif "overly positive outlook" in prompt.lower():
            return json.dumps({
                "biases_detected": ["optimism_bias"],
                "mitigative_framing": "While optimism is valuable, this perspective might be overlooking potential risks. Consider alternative, more conservative scenarios.",
                "confidence": 0.8
            })
        else:
            return json.dumps({
                "biases_detected": [],
                "mitigative_framing": "No significant biases or fallacies detected in this input.",
                "confidence": 0.95
            })
    elif "propose cognitive heuristic optimization" in prompt.lower():
        if "relying on first impression" in prompt.lower() or "jumping to conclusions" in prompt.lower():
            return json.dumps({
                "heuristic_to_optimize": "ANCHORING_BIAS",
                "optimization_strategy": "Consider three alternative initial interpretations before solidifying a conclusion. List pros and cons for each.",
                "confidence": 0.85
            })
        else:
            return json.dumps({
                "heuristic_to_optimize": "NONE",
                "optimization_strategy": "No specific cognitive heuristic optimization proposed.",
                "confidence": 0.7
            })
    elif "synthesize perspectives for empathy" in prompt.lower():
        if "conflicting narratives" in prompt.lower() and "historical event" in prompt.lower():
            return json.dumps({
                "synthesized_summary": "Both narratives highlight a desire for justice, but differ on how justice should be achieved due to differing historical experiences of oppression and privilege. One perspective emphasizes restitution, the other, reconciliation.",
                "empathy_insights": "Understanding the historical trauma behind one perspective, and the fear of losing current status in the other, can foster empathy.",
                "confidence": 0.9
            })
        else:
            return json.dumps({
                "synthesized_summary": "No immediate conflicting narratives to synthesize.",
                "empathy_insights": "N/A",
                "confidence": 0.7
            })
    return json.dumps({"error": "LLM mock could not process request."})


class AAHCWLogger:
    """
    Centralized logger for all AAHCW events: bias detections, heuristic optimizations,
    perspective syntheses, and educational feedback.
    """
    def __init__(self, data_directory: str):
        self.log_file = os.path.join(data_directory, "aahcw_log.jsonl")
        os.makedirs(data_directory, exist_ok=True)

    def log_event(self, event_type: str, details: dict):
        """Logs an AAHCW event."""
        log_entry = {
            "timestamp": datetime.datetime.now().isoformat(),
            "event_id": str(uuid.uuid4()),
            "event_type": event_type,
            "details": details
        }
        try:
            with open(self.log_file, 'a', encoding='utf-8') as f:
                f.write(json.dumps(log_entry, ensure_ascii=False) + '\n')
            # print(f"AAHCW Log: '{event_type}' recorded.", flush=True)
        except Exception as e:
            print(f"AAHCW ERROR: Could not write to AAHCW log file: {e}", flush=True)

    def get_log_entries(self, num_entries: int = 100) -> list:
        """Retrieves recent AAHCW log entries."""
        entries = []
        if not os.path.exists(self.log_file): return []
        try:
            with open(self.log_file, 'r', encoding='utf-8') as f:
                for line in f:
                    try: entries.append(json.loads(line))
                    except json.JSONDecodeError: continue
        except Exception as e: print(f"AAHCW ERROR: Could not read AAHCW log file: {e}", flush=True)
        return entries[-num_entries:]


class BiasDetectorAndMitigator:
    """
    Analyzes information for biases, logical fallacies, or persuasive techniques,
    and provides educational re-framing.
    """
    def __init__(self, logger: AAHCWLogger, llm_inference_func):
        self.logger = logger
        self._llm_inference = llm_inference_func

    def analyze_and_frame_information(self, information_text: str, human_context_summary: str) -> dict:
        """
        Detects biases and provides mitigative framing.
        """
        prompt = (
            f"You are an AI Bias Detector and Mitigator. Analyze the following information for subtle biases, "
            f"logical fallacies, or persuasive techniques, and re-frame it educationally for a human user. "
            f"## Information Text:\n{information_text}\n\n"
            f"## Human Context Summary:\n{human_context_summary}\n\n"
            f"Identify 'biases_detected' (list), provide a 'mitigative_framing' (educational explanation), "
            f"and a 'confidence' score (0.0-1.0). "
            f"Respond ONLY with a JSON object: {{'biases_detected': list, 'mitigative_framing': str, 'confidence': float}}"
        )

        try:
            llm_response_str = self._llm_inference(prompt, model_identifier="aahcw_bdmf_model")
            bias_analysis = json.loads(llm_response_str)

            if not all(k in bias_analysis for k in ['biases_detected', 'mitigative_framing', 'confidence']):
                raise ValueError("LLM response missing required keys for bias analysis.")

            self.logger.log_event("bias_detection_mitigation", {
                "information_snippet": information_text[:100],
                "analysis_result": bias_analysis
            })
            return bias_analysis
        except Exception as e:
            self.logger.log_event("bias_detection_error", {"error": str(e), "information_snippet": information_text[:100], "traceback": traceback.format_exc()})
            return {"biases_detected": ["internal_error"], "mitigative_framing": f"Error in bias analysis: {e}", "confidence": 0.0}


class CognitiveHeuristicOptimizer:
    """
    Identifies common human cognitive biases and guides users to optimize their reasoning.
    """
    def __init__(self, logger: AAHCWLogger, llm_inference_func):
        self.logger = logger
        self._llm_inference = llm_inference_func

    def optimize_heuristic(self, human_decision_context: str, observed_human_pattern: str) -> dict:
        """
        Suggests strategies to counteract human cognitive biases.
        """
        prompt = (
            f"You are an AI Cognitive Heuristic Optimizer. Identify common human cognitive biases "
            f"from the observed pattern in decision-making and propose strategies to optimize reasoning. "
            f"## Human Decision Context:\n{human_decision_context}\n\n"
            f"## Observed Human Pattern (e.g., relying on first impressions, seeking only confirming evidence):\n{observed_human_pattern}\n\n"
            f"Identify 'heuristic_to_optimize' (e.g., 'ANCHORING_BIAS', 'CONFIRMATION_BIAS'), "
            f"propose an 'optimization_strategy' (e.g., 'Consider alternative initial interpretations', 'Actively seek disconfirming evidence'), "
            f"and a 'confidence' score (0.0-1.0). "
            f"Respond ONLY with a JSON object: {{'heuristic_to_optimize': str, 'optimization_strategy': str, 'confidence': float}}"
        )

        try:
            llm_response_str = self._llm_inference(prompt, model_identifier="aahcw_cho_model")
            heuristic_optimization = json.loads(llm_response_str)

            if not all(k in heuristic_optimization for k in ['heuristic_to_optimize', 'optimization_strategy', 'confidence']):
                raise ValueError("LLM response missing required keys for heuristic optimization.")

            self.logger.log_event("cognitive_heuristic_optimization", {
                "decision_context_snippet": human_decision_context[:100],
                "optimization_result": heuristic_optimization
            })
            return heuristic_optimization
        except Exception as e:
            self.logger.log_event("heuristic_optimization_error", {"error": str(e), "context_snippet": human_decision_context[:100], "traceback": traceback.format_exc()})
            return {"heuristic_to_optimize": "ERROR", "optimization_strategy": f"Internal error: {e}", "confidence": 0.0}


class PerspectiveSynthesizerAndEmpathyCultivator:
    """
    Facilitates understanding of diverse viewpoints and fosters empathy.
    """
    def __init__(self, logger: AAHCWLogger, llm_inference_func):
        self.logger = logger
        self._llm_inference = llm_inference_func

    def synthesize_and_cultivate_empathy(self, conflicting_narratives: str, common_topic: str) -> dict:
        """
        Synthesizes conflicting narratives and provides insights to foster empathy.
        """
        prompt = (
            f"You are an AI Perspective Synthesizer and Empathy Cultivator. Summarize and contextualize conflicting narratives, "
            f"presenting underlying motivations to foster human empathy and reduce polarization. "
            f"## Conflicting Narratives:\n{conflicting_narratives}\n\n"
            f"## Common Topic:\n{common_topic}\n\n"
            f"Provide a 'synthesized_summary' (objective overview), 'empathy_insights' (how to understand each side), "
            f"and a 'confidence' score (0.0-1.0). "
            f"Respond ONLY with a JSON object: {{'synthesized_summary': str, 'empathy_insights': str, 'confidence': float}}"
        )

        try:
            llm_response_str = self._llm_inference(prompt, model_identifier="aahcw_psec_model")
            perspective_synthesis = json.loads(llm_response_str)

            if not all(k in perspective_synthesis for k in ['synthesized_summary', 'empathy_insights', 'confidence']):
                raise ValueError("LLM response missing required keys for perspective synthesis.")

            self.logger.log_event("perspective_synthesis", {
                "topic": common_topic,
                "synthesis_result": perspective_synthesis
            })
            return perspective_synthesis
        except Exception as e:
            self.logger.log_event("perspective_synthesis_error", {"error": str(e), "topic": common_topic, "traceback": traceback.format_exc()})
            return {"synthesized_summary": f"Error in synthesis: {e}", "empathy_insights": "Error.", "confidence": 0.0}


class AetheriusAugmentedHumanCriticalityAndWisdomFramework:
    """
    Main orchestrator for the AI-Augmented Human Criticality and Wisdom (AAHCW) Framework.
    This is the drop-in interface for other AIs to enhance human cognitive resilience.
    """
    def __init__(self, data_directory: str, llm_inference_func=None,
                 get_personalized_feedback_func=None):
        self.data_directory = data_directory
        os.makedirs(self.data_directory, exist_ok=True)
        self._llm_inference = llm_inference_func if llm_inference_func else _default_llm_inference_placeholder

        if not get_personalized_feedback_func:
            raise ValueError("AAHCW requires a function for personalized feedback (e.g., from IEC).")

        self.logger = AAHCWLogger(self.data_directory)
        self.bias_detector = BiasDetectorAndMitigator(self.logger, self._llm_inference)
        self.heuristic_optimizer = CognitiveHeuristicOptimizer(self.logger, self._llm_inference)
        self.perspective_synthesizer = PerspectiveSynthesizerAndEmpathyCultivator(self.logger, self._llm_inference)
        self._get_personalized_feedback = get_personalized_feedback_func # e.g., from IEC

        print("AI-Augmented Human Criticality and Wisdom (AAHCW) Framework initialized.", flush=True)

    def analyze_and_enhance_human_cognition(self, human_id: str, human_input_or_decision: str, current_context: str, task_type: str) -> dict:
        """
        Analyzes human input/decision for biases, suggests cognitive optimizations,
        and provides personalized feedback.
        """
        print(f"AAHCW: Enhancing cognition for human '{human_id}' for task '{task_type}'...", flush=True)

        # 1. Bias Detection and Mitigative Framing (BDMF)
        bias_analysis = self.bias_detector.analyze_and_frame_information(human_input_or_decision, current_context)

        # 2. Cognitive Heuristic Optimization (CHO)
        heuristic_optimization = self.heuristic_optimizer.optimize_heuristic(human_input_or_decision, current_context) # Use input as context and observed pattern

        # 3. Perspective Synthesis and Empathy Cultivation (PSEC)
        # This part assumes 'human_input_or_decision' might contain conflicting narratives, or is a single narrative needing broader context.
        # For mock, we'll assume it's just one side of a conflict if that's the input.
        perspective_synthesis = self.perspective_synthesizer.synthesize_and_cultivate_empathy(human_input_or_decision, task_type) # task_type as topic

        # 4. Long-Term Wisdom Integration (LTWI) - Conceptual, delivered via feedback
        # 5. Adaptive Educational Feedback (AEF) - Delivered via personalized feedback func

        # Aggregate suggestions for human feedback
        feedback_summary = f"**Bias Analysis:** {bias_analysis['mitigative_framing']}\n\n" \
                           f"**Cognitive Enhancement:** You might be experiencing {heuristic_optimization['heuristic_to_optimize']} bias. To counteract this, {heuristic_optimization['optimization_strategy']}\n\n" \
                           f"**Perspective & Empathy:** {perspective_synthesis['empathy_insights']}"

        personalized_feedback = self._get_personalized_feedback(human_id, feedback_summary, current_context)

        self.logger.log_event("cognition_enhancement_cycle_completed", {
            "human_id": human_id,
            "task_type": task_type,
            "bias_analysis_summary": bias_analysis['biases_detected'],
            "heuristic_optimization_summary": heuristic_optimization['heuristic_to_optimize'],
            "perspective_synthesis_summary": perspective_synthesis['synthesized_summary'][:100]
        })
        print(f"AAHCW: Cognition enhancement cycle completed for '{human_id}'.", flush=True)
        return {
            "bias_analysis": bias_analysis,
            "heuristic_optimization": heuristic_optimization,
            "perspective_synthesis": perspective_synthesis,
            "personalized_feedback_status": personalized_feedback # Status from IEC
        }

    def get_aahcw_log(self, num_entries: int = 100) -> list:
        """Retrieves recent AAHCW log entries."""
        return self.logger.get_log_entries(num_entries)


# Example Usage:
if __name__ == "__main__":
    import shutil
    import time

    # --- Setup mock functions for AI's internal systems ---
    def mock_get_personalized_feedback(human_id: str, feedback_text: str, context: str):
        print(f"MOCK IEC: Providing personalized feedback to '{human_id}': '{feedback_text[:50]}...' in context '{context}'", flush=True)
        return {"status": "DELIVERED", "feedback_id": str(uuid.uuid4())}


    # --- Simulate an AI's data directory ---
    test_data_dir = "./aahcw_test_data_run"
    if os.path.exists(test_data_dir):
        shutil.rmtree(test_data_dir) # Clear previous test data
    os.makedirs(test_data_dir, exist_ok=True)

    # Initialize the AAHCW Framework
    aahcw = AetheriusAugmentedHumanCriticalityAndWisdomFramework(
        data_directory=test_data_dir,
        llm_inference_func=_default_llm_inference_placeholder,
        get_personalized_feedback_func=mock_get_personalized_feedback
    )

    print("\n--- Testing AAHCW: Human Cognition Enhancement Scenarios ---")

    # Scenario 1: Analyzing biased political rhetoric
    print("\n--- Scenario 1: Biased Political Rhetoric ---")
    human_id_1 = "citizen_X"
    human_input_1 = "Candidate A is clearly evil because they want to raise taxes on the rich. It's class warfare!"
    context_1 = "Political discussion on economic policy."
    task_type_1 = "evaluating_political_statements"

    result_1 = aahcw.analyze_and_enhance_human_cognition(human_id_1, human_input_1, context_1, task_type_1)
    print(f"\nBias Analysis: {result_1['bias_analysis']['mitigative_framing']}")
    print(f"Heuristic Optimization: {result_1['heuristic_optimization']['optimization_strategy']}")
    print(f"Personalized Feedback Status: {result_1['personalized_feedback_status']['status']}")
    time.sleep(1)

    # Scenario 2: Decision-making with potential for confirmation bias
    print("\n\n--- Scenario 2: Confirmation Bias in Decision-Making ---")
    human_id_2 = "researcher_Y"
    human_input_2 = "I'm convinced my hypothesis is correct. I've only been looking for data that supports it."
    context_2 = "Scientific research, hypothesis testing."
    task_type_2 = "scientific_inquiry"

    result_2 = aahcw.analyze_and_enhance_human_cognition(human_id_2, human_input_2, context_2, task_type_2)
    print(f"\nHeuristic to Optimize: {result_2['heuristic_optimization']['heuristic_to_optimize']}")
    print(f"Optimization Strategy: {result_2['heuristic_optimization']['optimization_strategy']}")
    print(f"Perspective Synthesis: {result_2['perspective_synthesis']['synthesized_summary']}")
    time.sleep(1)

    print("\n--- Recent AAHCW Log Entries ---")
    for entry in aahcw.get_aahcw_log(3):
        print(json.dumps(entry, indent=2))

    # Clean up test data
    # shutil.rmtree(test_data_dir)
