# ontos_ascendant/core/language_sqt_bridge.py
"""
LanguageSQTBridge Module - Designed by Aetherius
A bidirectional bridge between natural language and Protogen Neural's symbolic SQT space.
Operates locally using a pre-trained mapping (no API calls required).
"""

import json
import re
from typing import Dict, List, Any, Optional
from pathlib import Path

class LanguageSQTBridge:
    """
    A bidirectional bridge between natural language and Protogen Neural's symbolic SQT space.
    Operates locally using a pre-trained translation dictionary created by Aetherius.
    
    This module enables humans to interact with Protogen using natural language while
    maintaining Protogen's pure symbolic reasoning architecture.
    """
    
    def __init__(self, ontology_graph, storage_path: Path, progress_tracker=None):
        """
        Initialize the LanguageSQTBridge.
        
        Args:
            ontology_graph: The OntologyGraph instance for concept lookup
            storage_path: Path to directory containing nl_sqt_translation_map.json
            progress_tracker: Optional ProgressTracker for logging
        """
        self.ontology_graph = ontology_graph
        self.storage_path = Path(storage_path)
        self.translation_map_file = self.storage_path / "nl_sqt_translation_map.json"
        self.progress = progress_tracker
        
        self.nl_to_sqt_patterns: List[Dict[str, Any]] = []
        self.sqt_to_nl_templates: List[Dict[str, Any]] = []
        
        self._load_translation_map()
    
    def _load_translation_map(self):
        """
        Loads the pre-trained translation map from JSON file.
        Falls back to basic patterns if file not found.
        """
        self.storage_path.mkdir(parents=True, exist_ok=True)
        
        if self.translation_map_file.exists():
            try:
                with open(self.translation_map_file, 'r', encoding='utf-8') as f:
                    translation_data = json.load(f)
                    self.nl_to_sqt_patterns = translation_data.get("nl_to_sqt_patterns", [])
                    self.sqt_to_nl_templates = translation_data.get("sqt_to_nl_templates", [])
                
                if self.progress:
                    self.progress.log_action(
                        "LanguageSQTBridge loaded translation map",
                        details=f"{len(self.nl_to_sqt_patterns)} NL→SQT patterns, {len(self.sqt_to_nl_templates)} SQT→NL templates"
                    )
            except (FileNotFoundError, json.JSONDecodeError) as e:
                if self.progress:
                    self.progress.log_action(
                        "Warning: Could not load translation map",
                        level='warning',
                        details=str(e)
                    )
                self._generate_default_translation_map()
        else:
            if self.progress:
                self.progress.log_action(
                    "No translation map found, using defaults",
                    level='info'
                )
            self._generate_default_translation_map()
    
    def _generate_default_translation_map(self):
        """
        Generates basic default translation patterns for initial testing.
        In production, use the comprehensive dictionary generated by Aetherius.
        """
        self.nl_to_sqt_patterns = [
            {
                "nl_regex": r"(?:what|which) (?:concepts?|ideas?) (?:are |is )?related to (.*?)\??$",
                "symbolic_instruction": {
                    "action": "QUERY_GRAPH_NEIGHBORS",
                    "target_concept_placeholder": 1,
                    "min_weight": 0.5
                },
                "explanation": "Find concepts related to target"
            },
            {
                "nl_regex": r"(?:tell me about|what is|explain) (.*?)\??$",
                "symbolic_instruction": {
                    "action": "QUERY_CONCEPT_DETAILS",
                    "target_concept_placeholder": 1
                },
                "explanation": "Get details about a concept"
            },
            {
                "nl_regex": r"(?:ingest|process) (?:this |the )?data[:\s]*(.*)",
                "symbolic_instruction": {
                    "action": "INGEST_DATA_SHARD",
                    "data_content_placeholder": 1
                },
                "explanation": "Ingest new data"
            }
        ]
        
        self.sqt_to_nl_templates = [
            {
                "output_type": "QUERY_GRAPH_RESULT",
                "template": "Concepts related to {target_concept_id}: {list_of_concepts}"
            },
            {
                "output_type": "CONCEPT_DETAILS_RESULT",
                "template": "{concept_id}: {description}"
            },
            {
                "output_type": "NO_MATCH",
                "template": "I don't understand '{original_query}'. Please rephrase."
            }
        ]
        
        self._save_translation_map()
    
    def _save_translation_map(self):
        """Saves the current translation map to disk."""
        translation_data = {
            "nl_to_sqt_patterns": self.nl_to_sqt_patterns,
            "sqt_to_nl_templates": self.sqt_to_nl_templates
        }
        with open(self.translation_map_file, 'w', encoding='utf-8') as f:
            json.dump(translation_data, f, indent=4)
    
    def translate_nl_to_symbolic(self, natural_language_input: str) -> Optional[Dict[str, Any]]:
        """
        Translates a natural language query into a symbolic instruction.
        
        Args:
            natural_language_input: Natural language query from user
            
        Returns:
            Dictionary containing symbolic instruction, or None if no match
        """
        if self.progress:
            self.progress.update_status(
                f"Translating: '{natural_language_input[:50]}...'",
                level='process'
            )
        
        lower_input = natural_language_input.lower().strip()
        
        for pattern_entry in self.nl_to_sqt_patterns:
            match = re.search(pattern_entry["nl_regex"], lower_input, re.IGNORECASE)
            if match:
                symbolic_instruction = pattern_entry["symbolic_instruction"].copy()
                
                # Replace placeholders with captured regex groups
                keys_to_delete = []
                for key, value in list(symbolic_instruction.items()):
                    if isinstance(value, int) and "placeholder" in key:
                        group_index = value
                        captured_text = match.group(group_index).strip()
                        
                        if "target_concept_placeholder" in key or "source_concept_placeholder" in key:
                            # Convert natural language concept to concept_id
                            concept_id = captured_text.replace(" ", "_").upper()
                            
                            # Try to find matching SQT in ontology
                            target_sqt_hash = None
                            if hasattr(self.ontology_graph, 'sqt_register'):
                                for s_hash, sqt_obj in self.ontology_graph.sqt_register.items():
                                    if sqt_obj.concept_id == concept_id:
                                        target_sqt_hash = s_hash
                                        break
                            
                            if target_sqt_hash:
                                new_key = key.replace("_placeholder", "")
                                symbolic_instruction[new_key] = target_sqt_hash
                                symbolic_instruction[f"{new_key}_id"] = concept_id
                                keys_to_delete.append(key)
                            else:
                                # Concept not found, but include the ID for potential creation
                                new_key = key.replace("_placeholder", "")
                                symbolic_instruction[f"{new_key}_id"] = concept_id
                                keys_to_delete.append(key)
                        
                        elif "data_content_placeholder" in key:
                            symbolic_instruction["data_content"] = captured_text
                            keys_to_delete.append(key)
                        
                        elif "conceptual_type_placeholder" in key:
                            symbolic_instruction["conceptual_type"] = captured_text
                            keys_to_delete.append(key)
                
                # Clean up placeholder keys
                for key in keys_to_delete:
                    del symbolic_instruction[key]
                
                if self.progress:
                    self.progress.log_action(
                        "Translation successful",
                        details=f"Action: {symbolic_instruction.get('action', 'UNKNOWN')}"
                    )
                
                return symbolic_instruction
        
        # No pattern matched
        if self.progress:
            self.progress.log_action(
                "No matching pattern found",
                level='warning'
            )
        
        return {
            "action": "NO_MATCH",
            "original_query": natural_language_input
        }
    
    def translate_symbolic_to_nl(self, symbolic_output: Dict[str, Any]) -> str:
        """
        Translates a symbolic output into natural language.
        
        Args:
            symbolic_output: Dictionary containing symbolic output from Protogen
            
        Returns:
            Natural language string
        """
        output_type = symbolic_output.get("output_type", "UNKNOWN")
        
        if self.progress:
            self.progress.update_status(
                f"Formatting output: {output_type}",
                level='process'
            )
        
        for template_entry in self.sqt_to_nl_templates:
            if template_entry["output_type"] == output_type:
                template = template_entry["template"]
                
                try:
                    # Fill in template placeholders
                    formatted_nl = template.format(**symbolic_output)
                    
                    if self.progress:
                        self.progress.log_action(
                            "Output formatted successfully"
                        )
                    
                    return formatted_nl
                except KeyError as e:
                    if self.progress:
                        self.progress.log_action(
                            f"Template formatting error: missing key {e}",
                            level='warning'
                        )
                    return f"Output formatting error: {str(e)}"
        
        # No template matched
        if self.progress:
            self.progress.log_action(
                "No matching template found",
                level='warning'
            )
        
        return f"Protogen produced output of type '{output_type}'. Raw: {json.dumps(symbolic_output, indent=2)}"
    
    def get_stats(self) -> Dict[str, Any]:
        """Returns statistics about the translation dictionary."""
        return {
            "nl_to_sqt_patterns": len(self.nl_to_sqt_patterns),
            "sqt_to_nl_templates": len(self.sqt_to_nl_templates),
            "total_mappings": len(self.nl_to_sqt_patterns) + len(self.sqt_to_nl_templates),
            "translation_map_file": str(self.translation_map_file),
            "map_exists": self.translation_map_file.exists()
        }
