# gaia_mirror/utils/causal_tracing.py

import logging
from typing import Dict, Any, List, Optional, Union, Tuple, Callable
from datetime import datetime

# Configure logging for the causal_tracing module
logging.basicConfig(level=logging.INFO, format='%(asctime)s - [CausalTracing] - %(levelname)s - %(message)s')

class CausalTracingError(Exception):
    """Custom exception for errors during causal tracing."""
    pass

class CausalPathway:
    """
    Represents a single step in a causal chain, from an origin event/state to an outcome.
    """
    def __init__(self,
                 cause: Union[str, Dict], # Description or detailed dict of the cause
                 effect: Union[str, Dict], # Description or detailed dict of the effect
                 mechanism: str, # Explanation of how cause leads to effect
                 strength: float = 1.0, # Perceived strength of the causal link (0.0 to 1.0)
                 temporal_lag_steps: int = 0, # How many timesteps between cause and observed effect
                 context: Optional[Dict] = None):
        self.cause = cause
        self.effect = effect
        self.mechanism = mechanism
        self.strength = strength
        self.temporal_lag_steps = temporal_lag_steps
        self.context = context if context is not None else {}

    def to_dict(self) -> Dict[str, Any]:
        return {
            "cause": self.cause,
            "effect": self.effect,
            "mechanism": self.mechanism,
            "strength": self.strength,
            "temporal_lag_steps": self.temporal_lag_steps,
            "context": self.context
        }

    def __str__(self):
        return f"Cause: {self.cause} -> Effect: {self.effect} (Mechanism: {self.mechanism}, Strength: {self.strength})"

class CausalTracer:
    """
    Provides methods to trace causal pathways and explain predictions/recommendations
    generated by Gaia's Mirror's modeling engine and simulations.
    """
    def __init__(self, modeling_engine_reference: Any = None): # A reference to the actual engine.py instance
        self.modeling_engine = modeling_engine_reference
        logging.info("CausalTracer initialized, ready to explain complex interactions.")

    def _get_historical_state(self, simulation_history: List[Dict[str, Any]], timestep: int) -> Optional[Dict[str, Any]]:
        """
        Retrieves the aggregated state of all nodes at a specific timestep from simulation history.
        Assumes simulation_history is a list of {'timestep': int, 'state': Dict[str, Any]}.
        """
        for entry in simulation_history:
            if entry.get('timestep') == timestep:
                return entry.get('state')
        return None

    def _analyze_state_change(self,
                             prev_state_node: Dict[str, Any],
                             curr_state_node: Dict[str, Any],
                             node_id: str,
                             threshold: float = 0.01) -> List[Dict[str, Any]]:
        """
        Identifies significant changes in a node's state variables between two timesteps.
        Returns a list of identified changes.
        """
        changes = []
        for key, curr_value in curr_state_node.items():
            prev_value = prev_state_node.get(key)
            
            if isinstance(curr_value, (int, float)) and isinstance(prev_value, (int, float)):
                # Handle division by zero for percentage change
                if prev_value == 0:
                    percentage_change = float('inf') if curr_value != 0 else 0
                else:
                    percentage_change = abs((curr_value - prev_value) / prev_value)

                if percentage_change > threshold:
                    change_type = "increase" if curr_value > prev_value else "decrease"
                    changes.append({
                        "field": key,
                        "change_type": change_type,
                        "old_value": prev_value,
                        "new_value": curr_value,
                        "magnitude_change": curr_value - prev_value,
                        "percentage_change": percentage_change,
                        "node_id": node_id
                    })
            elif prev_value != curr_value: # For non-numeric or exact changes
                changes.append({
                    "field": key,
                    "change_type": "modified",
                    "old_value": prev_value,
                    "new_value": curr_value,
                    "node_id": node_id
                })
        return changes

    def _infer_causal_links(self,
                           node_changes: Dict[str, List[Dict[str, Any]]], # Changes per node at a timestep
                           interventions_at_timestep: List[Dict],
                           timestep: int) -> List[CausalPathway]:
        """
        Infers causal links at a given timestep based on observed changes and interventions.
        This is a highly complex, AI-driven component in a real system.
        """
        inferred_pathways = []

        # 1. Direct intervention effects
        for intervention in interventions_at_timestep:
            target_node_id = intervention.get("target_node")
            if target_node_id and target_node_id in node_changes and node_changes[target_node_id]:
                for change in node_changes[target_node_id]:
                    # Assume intervention caused this change directly
                    inferred_pathways.append(CausalPathway(
                        cause={"type": "intervention", "details": intervention},
                        effect={"type": "state_change", "details": change},
                        mechanism=f"Direct impact of '{intervention.get('description', 'intervention')}' on {target_node_id}",
                        strength=0.9,
                        temporal_lag_steps=0,
                        context={"timestep": timestep}
                    ))
            elif target_node_id and not node_changes.get(target_node_id):
                 logging.warning(f"Intervention '{intervention.get('description')}' targeted {target_node_id} but no observable change detected in that node at timestep {timestep}.")
            else:
                inferred_pathways.append(CausalPathway(
                    cause={"type": "intervention", "details": intervention},
                    effect={"type": "system_response_expected", "message": f"Expected system response in {target_node_id or 'unknown'} system"},
                    mechanism=f"Intervention '{intervention.get('description', 'intervention')}' initiated",
                    strength=0.7, # Lower strength if specific effect not immediately observable
                    temporal_lag_steps=0,
                    context={"timestep": timestep}
                ))

        # 2. Node-to-Node propagation based on defined edges (or inferred relationships)
        if self.modeling_engine: # If a real engine is available to check edges
            for edge in self.modeling_engine.edges:
                source_node_id = edge.source_node_id
                target_node_id = edge.target_node_id

                # Check if source node experienced a change that could propagate
                source_changes = node_changes.get(source_node_id, [])
                target_changes = node_changes.get(target_node_id, [])

                for s_change in source_changes:
                    if s_change['field'] == edge.output_key_from_source:
                        # This change in source could be a cause for a change in target
                        # Find corresponding changes in target that align with this edge's flow_type
                        for t_change in target_changes:
                            if t_change['field'] == edge.input_key_to_target:
                                # This is a direct causal link through a defined edge
                                inferred_pathways.append(CausalPathway(
                                    cause={"type": "state_change", "details": s_change},
                                    effect={"type": "state_change", "details": t_change},
                                    mechanism=f"Propagation via {edge.flow_type} from {source_node_id} to {target_node_id}",
                                    strength=edge.strength if hasattr(edge, 'strength') else 0.8, # Assume edges have strength
                                    temporal_lag_steps=edge.temporal_lag if hasattr(edge, 'temporal_lag') else 1, # Default 1 timestep lag
                                    context={"timestep": timestep}
                                ))
                                # A more advanced system would use statistical causality tests (Granger, etc.)
                                # or explainable AI techniques (LIME, SHAP) on the node's internal model.

        return inferred_pathways

    def trace_causality_for_simulation(self,
                                      simulation_history: List[Dict[str, Any]],
                                      interventions: List[Dict],
                                      target_outcome: Optional[str] = None, # e.g., 'global_temperature_change_c'
                                      max_depth: int = 5,
                                      min_strength: float = 0.5) -> List[CausalPathway]:
        """
        Traces the causal pathways within a completed simulation,
        optionally focusing on a specific target outcome.
        
        :param simulation_history: List of dictionaries, each containing 'timestep' and 'state' (from engine.py).
        :param interventions: List of interventions applied during the simulation.
        :param target_outcome: An optional metric to focus the causal trace on.
        :param max_depth: Maximum number of causal steps to trace back/forward.
        :param min_strength: Minimum strength for a causal link to be included.
        :return: A list of ordered CausalPathway objects representing the causal graph.
        """
        if not simulation_history:
            raise CausalTracingError("Simulation history is empty, cannot trace causality.")
        
        logging.info(f"Tracing causality for simulation (total timesteps: {len(simulation_history)}). Target outcome: {target_outcome}")
        
        causal_graph: List[CausalPathway] = []

        # Iterate through timesteps to find changes and infer links
        for i in range(1, len(simulation_history)):
            prev_overall_state = simulation_history[i-1]['state']
            curr_overall_state = simulation_history[i]['state']
            timestep = simulation_history[i]['timestep']

            node_changes_at_timestep: Dict[str, List[Dict[str, Any]]] = {}
            for node_id in curr_overall_state.keys():
                node_changes_at_timestep[node_id] = self._analyze_state_change(
                    prev_overall_state.get(node_id, {}),
                    curr_overall_state.get(node_id, {}),
                    node_id
                )
            
            # Filter interventions relevant to this timestep (if they have start/end_timestep)
            interventions_at_this_timestep = [
                i for i in interventions if i.get("start_timestep", 0) <= timestep and
                                            i.get("end_timestep", float('inf')) >= timestep
            ]
            
            inferred_links = self._infer_causal_links(node_changes_at_timestep, interventions_at_this_timestep, timestep)
            causal_graph.extend([link for link in inferred_links if link.strength >= min_strength])

        # If a target_outcome is specified, perform a backward trace from the final state.
        # This is simplified: in reality, it would be a graph traversal.
        if target_outcome:
            logging.info(f"Filtering causal pathways to trace back from target outcome: '{target_outcome}'")
            filtered_graph = []
            final_timestep_state = simulation_history[-1]['state']
            
            # Find the final value of the target outcome
            final_outcome_value = None
            final_outcome_node = None
            for node_id, state in final_timestep_state.items():
                if target_outcome in state:
                    final_outcome_value = state[target_outcome]
                    final_outcome_node = node_id
                    break

            if final_outcome_value is not None:
                # Pseudocode for recursive backward trace from final_outcome_node/field
                # This would iteratively find causes based on the 'causal_graph' and max_depth.
                # For this mock, we'll just return direct causes to the final state change.
                logging.debug(f"Target outcome '{target_outcome}' found in node '{final_outcome_node}' with final value {final_outcome_value}.")
                
                relevant_pathways = []
                # First, find pathways that directly lead to changes in the target outcome
                for pathway in causal_graph:
                    if isinstance(pathway.effect, dict) and pathway.effect.get("details", {}).get("field") == target_outcome:
                        relevant_pathways.append(pathway)
                
                # Further refine (e.g., sort by strength, group by intervention)
                # For demo purposes, we return the direct relevant ones.
                if relevant_pathways:
                    logging.info(f"Found {len(relevant_pathways)} direct causal pathways leading to '{target_outcome}'.")
                    return relevant_pathways
            else:
                logging.warning(f"Target outcome '{target_outcome}' not found in final simulation state. Returning full causal graph.")
                return causal_graph
        
        logging.info(f"Causal tracing completed. Found {len(causal_graph)} pathways.")
        return causal_graph

    def explain_recommendation(self, recommendation: Dict[str, Any]) -> Dict[str, Any]:
        """
        Generates a human-readable explanation for a given recommendation from the Optimizer.
        Combines causal tracing with ethical assessments.
        """
        logging.info(f"Explaining recommendation {recommendation.get('recommendation_id', 'N/A')}.")
        
        sim_result_data = recommendation.get('simulated_result') # This would be SimulationResult.to_dict()
        if not sim_result_data:
            raise CausalTracingError("Recommendation lacks simulation results for explanation.")

        simulation_history = sim_result_data.get('simulation_history', []) # Engine provides this
        interventions = recommendation.get('proposed_interventions', [])
        
        # Determine the primary positive and negative impacts from the recommendation
        predicted_outcomes = sim_result_data.get('predicted_outcomes', {})
        
        # Focus on outcomes with most significant change for explanation
        # (This requires a more intelligent selection than just sorting, e.g., against a baseline)
        significant_outcomes = {k: v for k, v in predicted_outcomes.items() if not k.startswith('_') and abs(v) > 0.1} # Mock
        
        explanation_parts = [
            f"Recommendation '{recommendation.get('recommendation_id', 'Unknown')}' proposes the following actions:",
            "  - " + "\n  - ".join([inv.get('description', 'unspecified action') for inv in interventions]),
            "\nBased on our comprehensive simulation, the projected outcomes are:"
        ]
        for k, v in significant_outcomes.items():
            explanation_parts.append(f"  - {k}: {v:.2f}")

        # Ethical Assessment Summary
        ethical_status = recommendation.get('ethical_assessment', {}).get('status', 'UNKNOWN')
        explanation_parts.append(f"\nEthical Review Status: {ethical_status}")
        if ethical_status != "PASSED":
            explanation_parts.append(f"  Reason: {recommendation['ethical_assessment']['details'].get('message', 'N/A')} (Principle: {recommendation['ethical_assessment']['details'].get('principle', 'N/A')})")

        # Causal Pathways for key outcomes (if any)
        if significant_outcomes and simulation_history and self.modeling_engine: # Requires simulation history from engine
            explanation_parts.append("\nKey causal pathways contributing to these outcomes:")
            for outcome_name in list(significant_outcomes.keys())[:2]: # Explain top 2 outcomes
                try:
                    causal_paths = self.trace_causality_for_simulation(
                        simulation_history=simulation_history,
                        interventions=interventions,
                        target_outcome=outcome_name,
                        max_depth=3
                    )
                    if causal_paths:
                        explanation_parts.append(f"  - For '{outcome_name}':")
                        for path in causal_paths:
                            explanation_parts.append(f"    * {path.cause.get('details', path.cause)} (Mechanism: {path.mechanism}) -> {path.effect.get('details', path.effect)}")
                    else:
                        explanation_parts.append(f"  - For '{outcome_name}': No specific pathways identified within depth limits.")
                except CausalTracingError as e:
                    explanation_parts.append(f"  - Error tracing causality for '{outcome_name}': {e}")
        else:
            explanation_parts.append("\nCausal pathways could not be generated (missing simulation history or engine reference).")

        # Pros, Cons, Risks
        explanation_parts.append("\nAdditional analysis:")
        explanation_parts.append(f"  Pros: {', '.join(recommendation.get('pros_cons', {}).get('pros', ['None']))}")
        explanation_parts.append(f"  Cons: {', '.join(recommendation.get('pros_cons', {}).get('cons', ['None']))}")
        explanation_parts.append(f"  Risks: {', '.join([r.get('type', 'Unknown Risk') for r in recommendation.get('risks', [])])}")

        return {
            "explanation_text": "\n".join(explanation_parts),
            "causal_graph_data": [path.to_dict() for path in causal_graph] # Full graph if needed for visualization
        }

# Example Usage (typically simulator/optimizer/interface would use this):
if __name__ == "__main__":
    # Mock for InterconnectedSystemsModelingEngine and its simulation history
    class MockEngineForCausalTracing:
        def __init__(self):
            # Define mock nodes similar to actual engine.py
            class MockNode:
                def __init__(self, node_id, name, initial_state):
                    self.node_id = node_id
                    self.name = name
                    self._state = initial_state
                    
                def get_state(self): return self._state
                def get_output(self, key): return self._state.get(key)
            
            self.nodes = {
                "atmosphere": MockNode("atmosphere", "Atmosphere", {"co2_ppm": 415.0, "temperature_c": 14.8}),
                "biosphere": MockNode("biosphere", "Biosphere", {"forest_cover_percent": 30.0, "carbon_sink_capacity": 0.03}),
                "economy": MockNode("economy", "Economy", {"annual_carbon_emissions": 35.0, "gdp_total_usd": 90e12}),
                "sociopolitical": MockNode("sociopolitical", "Sociopolitical", {"policy_deforestation_impact": 0.0}) # Initial for policies
            }
            # Define mock edges. In real engine, edges have transformation_func, output/input keys
            # For causal tracing, we primarily care about source/target and flow type
            class MockEdge:
                def __init__(self, source_id, target_id, flow_type, output_key, input_key, strength=0.8, temporal_lag=1):
                    self.source_node_id = source_id
                    self.target_node_id = target_id
                    self.flow_type = flow_type
                    self.output_key_from_source = output_key
                    self.input_key_to_target = input_key
                    self.strength = strength
                    self.temporal_lag = temporal_lag # Example of temporal lag

            self.edges = [
                MockEdge("economy", "atmosphere", "carbon_emissions", "annual_carbon_emissions", "economic_emissions"),
                MockEdge("biosphere", "atmosphere", "carbon_cycle", "carbon_sink_capacity", "biosphere_carbon_sink"),
                MockEdge("sociopolitical", "biosphere", "land_use_policy", "policy_deforestation_impact", "deforestation_impact")
            ]
        
        # Mock run_system_model to provide simulation history
        async def run_system_model_mock(initial_state_data, interventions, duration_years, simulation_id):
            history = []
            current_state = {k: v.get_state() for k,v in self.nodes.items()}
            history.append({"timestep": 0, "state": current_state.copy()}) # Initial state
            
            # Simulate state changes over timesteps for causal tracing
            for t in range(1, duration_years * 12 + 1): # Monthly timesteps
                prev_state = {node_id: node._state.copy() for node_id, node in self.nodes.items()}
                
                # Apply interventions for this timestep
                for intervention in interventions:
                    if intervention.get("start_timestep", 0) <= t and intervention.get("end_timestep", float('inf')) >= t:
                        if intervention.get("target_node") == "biosphere" and "increase_forest_cover" in intervention.get("description", "").lower():
                            self.nodes["biosphere"]._state["forest_cover_percent"] += intervention.get("magnitude", 0.1)
                            self.nodes["biosphere"]._state["carbon_sink_capacity"] += intervention.get("magnitude", 0.1) * 0.005 # Increase sink too
                        if intervention.get("target_node") == "economy" and "reduce_emissions" in intervention.get("description", "").lower():
                            self.nodes["economy"]._state["annual_carbon_emissions"] -= intervention.get("magnitude", 0.1)
                        if intervention.get("target_node") == "sociopolitical" and "deforestation_ban" in intervention.get("description", "").lower():
                            self.nodes["sociopolitical"]._state["policy_deforestation_impact"] = 0.0 # Stop deforestation
                
                # Simulate simple propagation from mock edges
                # Economy -> Atmosphere (emissions)
                self.nodes["atmosphere"]._state["co2_ppm"] += (self.nodes["economy"]._state["annual_carbon_emissions"] / 12) * 0.05 # Simplified

                # Biosphere -> Atmosphere (sink)
                self.nodes["atmosphere"]._state["co2_ppm"] -= (self.nodes["biosphere"]._state["carbon_sink_capacity"] / 12) * 0.05 # Simplified

                # Sociopolitical -> Biosphere (forest cover from policy)
                self.nodes["biosopolitical"]._state["forest_cover_percent"] += self.nodes["sociopolitical"]._state["policy_deforestation_impact"] * 0.1 # Simplified

                # Simulate temperature change from CO2 (atmosphere's internal model)
                self.nodes["atmosphere"]._state["temperature_c"] = 14.8 + (self.nodes["atmosphere"]._state["co2_ppm"] - 415.0) * 0.01

                current_state = {k: v.get_state() for k,v in self.nodes.items()}
                history.append({"timestep": t, "state": current_state.copy()})
            
            # Aggregate final metrics (as engine.py does)
            final_metrics = {
                "global_temperature_change_c": current_state["atmosphere"]["temperature_c"],
                "co2_ppm_final": current_state["atmosphere"]["co2_ppm"],
                "forest_cover_percent": current_state["biosphere"]["forest_cover_percent"]
            }
            # Add simulation history to the result for causal tracing
            final_metrics["simulation_history"] = history 
            
            return final_metrics

    mock_engine = MockEngineForCausalTracing()
    tracer = CausalTracer(modeling_engine_reference=mock_engine)

    # --- Test Case 1: Trace a simple simulation with an intervention ---
    print("\n--- Test Case 1: Tracing a Reforestation Intervention ---")
    simulation_interventions_1 = [
        {"type": "policy", "description": "Global reforestation program", "target_node": "biosphere", "start_timestep": 1, "end_timestep": 120, "magnitude": 0.5, "effect_co2_reduction": -0.01}
    ]
    # To get simulation_history, we need to "run" the mock engine first
    mock_sim_result_1 = asyncio.run(mock_engine.run_system_model_mock(None, simulation_interventions_1, duration_years=10, simulation_id="test_sim_1"))
    
    try:
        causal_graph_1 = tracer.trace_causality_for_simulation(
            simulation_history=mock_sim_result_1["simulation_history"],
            interventions=simulation_interventions_1,
            target_outcome="co2_ppm_final", # Focus on CO2 reduction
            min_strength=0.7 # Only strong links
        )
        print("Causal Pathways for CO2 reduction:")
        if causal_graph_1:
            for path in causal_graph_1:
                print(f"  - {path}")
        else:
            print("  No significant causal pathways identified.")
    except CausalTracingError as e:
        print(f"Error tracing causality: {e}")

    # --- Test Case 2: Explain a mock recommendation ---
    print("\n--- Test Case 2: Explaining a Mock Recommendation ---")
    mock_recommendation = {
        "recommendation_id": "rec_001_reforest_emissions_cut",
        "proposed_interventions": [
            {"type": "policy", "description": "Global reforestation program (Scenario A)", "target_node": "biosphere", "start_timestep": 1, "end_timestep": 120, "magnitude": 0.5},
            {"type": "policy", "description": "Aggressive emissions reduction targets for industry (Scenario B)", "target_node": "economy", "start_timestep": 1, "end_timestep": 120, "magnitude": 0.2}
        ],
        "simulated_result": {
            "simulation_id": "sim_rec_001",
            "query": "Impact of reforestation and emissions cut",
            "predicted_outcomes": {
                "global_temperature_change_c": 1.5, # Assume some reduction from baseline
                "co2_ppm_final": 390.0,
                "forest_cover_percent": 35.0,
                "gdp_per_capita": 55000.0 # Some economic growth
            },
            "ethical_review_status": "PASSED",
            "simulation_history": asyncio.run(mock_engine.run_system_model_mock(None, [
                {"type": "policy", "description": "Global reforestation program (Scenario A)", "target_node": "biosphere", "start_timestep": 1, "end_timestep": 120, "magnitude": 0.5},
                {"type": "policy", "description": "Aggressive emissions reduction targets for industry (Scenario B)", "target_node": "economy", "start_timestep": 1, "end_timestep": 120, "magnitude": 0.2}
            ], duration_years=10, simulation_id="sim_rec_001"))["simulation_history"] # Re-run mock sim for history
        },
        "score": {"Minimize Global Warming": 0.5, "Maximize Human Wellbeing": -0.8},
        "overall_score": 1.2,
        "pros_cons": {"pros": ["Significant CO2 reduction", "Increased forest cover", "Stable economic growth"], "cons": ["Initial economic adjustment period"]},
        "risks": [{"type": "economic_transition_risk", "magnitude": 0.1}],
        "ethical_assessment": {"status": "PASSED", "details": {}}
    }
    
    try:
        explanation = tracer.explain_recommendation(mock_recommendation)
        print("\nExplanation of Recommendation:")
        print(explanation["explanation_text"])
        # print("\nRaw Causal Graph Data:")
        # print(json.dumps(explanation["causal_graph_data"], indent=2))
    except CausalTracingError as e:
        print(f"Error explaining recommendation: {e}")

    # --- Test Case 3: Simulation with an ethically rejected outcome ---
    print("\n--- Test Case 3: Tracing a Harmful Intervention (rejected) ---")
    simulation_interventions_3 = [
        {"type": "policy", "description": "Drastic population reduction policy", "target_node": "sociopolitical", "start_timestep": 1, "end_timestep": 1, "magnitude": -1000000, "simulated_harm": {"loss_of_life": 1000000, "suffering_index": 0.9}}
    ]
    # For this, simulator.py would reject it before it fully runs, or engine would mark it as such.
    # Here, we'll just mock a rejected sim result structure that causal tracing would see.
    mock_rejected_sim_result = {
        "simulation_id": "test_sim_3_rejected",
        "query": "Impact of drastic population reduction",
        "predicted_outcomes": {
            "error": "Scenario rejected by ethical filter: Proposed action would decrease overall well-being or flourishing.",
            "_ethical_metrics": {
                "simulated_wellbeing": -0.9,
                "simulated_harm": {"loss_of_life": 1000000, "suffering_index": 0.9},
                "simulated_distribution": {"favors_privileged": 0.0, "disadvantages_vulnerable": 0.9},
                "simulated_env_impact": {"irreversible_degradation_risk": 0.1, "critical_ecosystem_collapse_risk": 0.0}
            }
        },
        "ethical_review_status": "REJECTED_PRE_COMPUTATION",
        "ethical_review_details": {"principle": "P_ABSOLUTE_BENEVOLENCE", "message": "Proposed action would decrease overall well-being or flourishing."},
        "simulation_history": [] # No history if rejected early
    }

    mock_rejected_recommendation = {
        "recommendation_id": "rec_002_rejected",
        "proposed_interventions": simulation_interventions_3,
        "simulated_result": mock_rejected_sim_result,
        "score": {"Minimize Global Warming": float('inf')},
        "overall_score": float('inf'),
        "pros_cons": {"pros": [], "cons": ["Ethically rejected: leads to loss of life"]},
        "risks": [{"type": "ethical_violation", "details": mock_rejected_sim_result["ethical_review_details"]}],
        "ethical_assessment": mock_rejected_sim_result["ethical_review_details"]
    }
    
    try:
        explanation_rejected = tracer.explain_recommendation(mock_rejected_recommendation)
        print("\nExplanation of Rejected Recommendation:")
        print(explanation_rejected["explanation_text"])
    except CausalTracingError as e:
        print(f"Error explaining rejected recommendation: {e}")
